# Generated by Django 5.0.6 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact',
            field=models.CharField(default='123', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(default='asd', max_length=3),
            preserve_default=False,
        ),
    ]
