# Generated by Django 5.0.6 on 2024-06-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_address_teacher_contact_teacher_teacher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
