# Generated by Django 5.0.6 on 2024-06-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_studentattendance_attendance_by'),
        ('courses', '0010_teacher_alter_subjectcourse_teacher'),
        ('notice', '0002_alter_notice_created_by'),
        ('teacher', '0003_remove_teacher_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
