# Generated by Django 5.0.6 on 2024-06-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_period_alter_class_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')]),
        ),
    ]
