# Generated by Django 5.0.6 on 2024-06-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_class_classroom_alter_period_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submittedassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='subjectcourse',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='SubmittedAssignment',
        ),
    ]
