# Generated by Django 5.0.6 on 2024-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_submittedassignment_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('Lec', 'Lecture'), ('Pra', 'Practical')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
