# Generated by Django 5.0.6 on 2024-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_class_group_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('-', 'Both')], max_length=1),
        ),
    ]
