# Generated by Django 5.0.6 on 2024-06-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_class_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='faculty',
            new_name='course',
        ),
    ]
