# Generated by Django 5.0.6 on 2024-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_class_teacher_subjectcourse_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='asd', max_length=5),
            preserve_default=False,
        ),
    ]
