# Generated by Django 5.0.6 on 2024-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_class_course_remove_class_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='group',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('-', 'Both')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(choices=[('Lec', 'Lecture'), ('Pra', 'Practical')], default='Lec', max_length=3),
        ),
    ]
