# Generated by Django 5.0.6 on 2024-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('Not', 'Notices'), ('Hol', 'Holiday')], default='Not', max_length=3),
            preserve_default=False,
        ),
    ]
