# Generated by Django 5.0.6 on 2024-06-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_submittedassignment_assignment_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Mor', 'Morning')], default='Day', max_length=3),
            preserve_default=False,
        ),
    ]
