# Generated by Django 5.0.6 on 2024-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_course_student_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_roll',
            field=models.TextField(default='Lec', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default='9841000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
