# Generated by Django 5.0.6 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_college_roll_student_contact_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
