# Generated by Django 5.0.6 on 2024-06-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
