# Generated by Django 5.0.6 on 2024-06-10 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_remove_submittedassignment_assignment_and_more'),
        ('student', '0002_student_course_student_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('submit_by', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_question')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_assignments')),
                ('grade', models.FloatField()),
                ('feedback', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ManyToManyField(through='assignment.Submission', to='student.student'),
        ),
    ]
