# Generated by Django 5.0.6 on 2024-06-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('courses', '0013_alter_class_group_alter_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teachersubjectconfig'),
        ),
    ]
