# Generated by Django 5.0.6 on 2024-07-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_assignment_assigned_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student',
            new_name='submissions',
        ),
    ]
