# Generated by Django 5.0.6 on 2024-06-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
