# Generated by Django 5.0.6 on 2024-06-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='date',
        ),
    ]
