# Generated by Django 5.0.6 on 2024-06-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_studentattendance_date'),
        ('courses', '0010_teacher_alter_subjectcourse_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher'),
        ),
    ]
