# Generated by Django 5.0.6 on 2024-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_studentattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='A', max_length=50),
        ),
    ]
