# Generated by Django 5.0.6 on 2024-06-15 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_studentattendance_status'),
        ('courses', '0013_alter_class_group_alter_class_type'),
        ('student', '0006_studentsubjectconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='A', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
