# Generated by Django 5.0.6 on 2024-06-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_customstudentattendance'),
        ('courses', '0013_alter_class_group_alter_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstudentattendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
