# Generated by Django 5.0.6 on 2024-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_customstudentattendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstudentattendance',
            name='period',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customstudentattendance',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Mor', 'Morning')], default='Mor', max_length=3),
            preserve_default=False,
        ),
    ]
