# Generated by Django 5.0.6 on 2024-06-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_customstudentattendance_period_and_more'),
        ('student', '0006_studentsubjectconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customstudentattendance',
            unique_together={('attendance_date', 'shift', 'period', 'student')},
        ),
    ]
